require('dotenv').config();
const { PORT = 8080 } = process.env;
import express from 'express';
import compression from 'compression';
import morgan from 'morgan';
import router from './server/router';
const app = express();
app.use(compression());
app.use(morgan('dev'));
app.use(router);
app.listen(PORT, () => console.log(`Listening on port ${PORT}!`));
