export default `
  type Mutation {
    createAddress(address:AddressInput): Address,
    createAndAssociateAddressToPerson(address:AddressInput, personId:Int): Address,
    updateOrChangeAddressByPersonId(address:AddressInput, personId:Int): Address,
    updateAddressById(id:Int, address:AddressInput): Address,
    associateAddressToPerson(id:Int, personId:Int): Person,
    deleteAddressById(id:Int): Address,
    createPerson(person:PersonInput): Person,
    updatePersonById(id:Int, person:PersonInput): Person,
    deletePersonById(id:Int): Person,
    createEvent(event:EventInput): Event,
    updateEventById(id:Int, event:EventInput): Event,
    deleteEventById(id:Int): Event,
    createAttendance(attendance:AttendanceInput): Attendance,
    updateAttendanceToEventByPersonId(id:Int, personId:Int, attendance:AttendanceInput): Attendance,
    createGroup(group:GroupoInput): Groupo,
    addToGroupByPersonId(id:Int, personId:Int): SuccessOrError,
    removeFromGroupByPersonId(id:Int, personId:Int): SuccessOrError,
    updateGroupById(id:Int, group:GroupoInput): Groupo,
    deleteGroupById(id:Int): Groupo,
    createLocation(location:LocationInput): Location,
    updateLocationById(id:Int, location:LocationInput): Location,
    deleteLocationById(id:Int): Location,
    createQuote(quote:QuoteInput): Quote,
    updateQuoteById(id:Int, quote:QuoteInput): Quote,
    deleteQuoteById(id:Int): Quote,
    addToQuoteByPersonId(id:Int, personId:Int): Quote
    createBlog(blog:BlogInput): Blog,
    updateBlogById(id:Int, blog:BlogInput): Blog,
    deleteBlogById(id:Int): Blog,
    createSong(song:SongInput): Song,
    updateSongById(id:Int, song:SongInput): Song,
    deleteSongById(id:Int): Song,
    createList(list:ListInput): List,
    updateListById(id:Int, list:ListInput): List,
    deleteListById(id:Int): List,
    addToListByPersonId(id:Int, personId:Int): List
  },
`;
